# Generated by Django 3.2.22 on 2023-10-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quetion',
            new_name='question',
        ),
    ]
